version: '3.7'
services:
    redis:
        image: "redis:alpine"
        container_name: my_redis
        command: redis-server --requirepass sOmE_sEcUrE_pAsS
        environment:
            - REDIS_REPLICATION_MODE=master
        ports:
            - "6379:6379"
        volumes:
            - ./data:/var/lib/redis
            - ./data:/usr/local/etc/redis/redis.conf
        networks:
            - webnet
        restart: always
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: be_api
        ports:
            - 9001:9001
        volumes:
            - "./api:/app"
        networks:
            - webnet
        restart: always
networks:
   webnet: